apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-prod
  namespace: observability
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.51
    options:
      memory:
        max-traces: 50000
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  storage:
    type: memory
    options:
      memory:
        max-traces: 50000
  ingress:
    enabled: false  # We'll create our own ingress with TLS
